Problem1/infoManage/infoManage/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('student.urls'))
]

Problem1/infoManage/student/urls.py
from django.urls import path
from . import views

app_name='student'
urlpatterns=[
    path('',views.index,name='index'),
    path('<str:roll>/delete/',views.deleteData,name='delete'),
    path('<str:roll>/edit/',views.editData,name='edit'),
    path('add/',views.addData,name='add'),
    path('savedata/',views.saveData,name='save'),
    path('<str:roll>/editdata/',views.editField,name='editdata')
]

Problem1/infoManage/student/models.py
from django.db import models

class StudentData(models.Model):
    name=models.CharField(max_length=250)
    roll=models.CharField(max_length=9,unique=True)
    department=models.CharField(max_length=100)
    hostel=models.CharField(max_length=50)

    def __str__(self):
        return self.roll

Problem1/infoManage/student/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import StudentData
def index (request):
    studentList=StudentData.objects.all()
    context={'studentList':studentList}
    return render(request,'student/index.html',context)
    # return HttpResponse("Hello, world!")

def deleteData(request,roll):
    # ent=StudentData.objects.get(roll=roll)
    StudentData.objects.filter(roll=roll).delete()
    # StudentData.save()
    return redirect('/')

def editData(request,roll):
    try:
        ent = StudentData.objects.get(roll=roll)
    except:
        return HttpResponse("Roll Number not valid")

    context={
        'name':ent.name,
        'roll':ent.roll,
        'hostel':ent.hostel,
        'department': ent.department
    }
    return render(request,'student/edit.html', context)

def addData(request):
    context={'ErrorMessage':''}
    return render(request,'student/add.html',context)
    # return index(request)


def saveData(request):
    sname=request.POST['name']
    sroll=request.POST['roll']
    sdept=request.POST['department']
    shostel=request.POST['hostel']
    a=StudentData(name=sname,roll=sroll,department=sdept,hostel=shostel)
    try:
        if sname=='' or sroll=='' or sdept=='' or shostel=='' :
            context = {'ErrorMessage': 'Data not valid'}
            return render(request, 'student/add.html', context)
        a.save()
        return redirect('/')
    except:
        context = {'ErrorMessage': 'Data not valid'}
        return render(request, 'student/add.html', context)


def editField(request,roll):
    try:
        ent=StudentData.objects.get(roll=roll)
    except:
        return HttpResponse("Roll Number not valid")
    ent.name=request.POST['name']
    ent.department=request.POST['department']
    ent.hostel=request.POST['hostel']
    try:
        ent.save()
    except:
        context={
            'ErrorMessage': 'Something went worng',
            'name':request.POST['name'],
            'department':request.POST['department'],
            'hostel':request.POST['hostel'],
            'roll':roll
        }
        return render(request,'student/edit.html',context)
    return redirect('/')

Problem1/infoManage/student/templates/student/add.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>add</title>#}
{#</head>#}
{#<body>#}
{#{{ ErrorMessage }}#}
{#    <form action="{% url 'student:save' %}" method="post">#}
{#        {%  csrf_token %}#}
{#        Name:<input name="name" value="{{ name }}"><br>#}
{#        Roll:<input name="roll" value="{{ roll }}"><br>#}
{#        Department:<input name="department" value="{{ dept }}"><br>#}
{#        Hostel:<input name="hostel" value="{{ hostel }}"><br>#}
{#        <input type="submit">#}
{#    </form>#}
{#</body>#}
{#</html>#}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>add</title>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <style>
      html, body {
      min-height: 100%;
      }
      body, div, form, input, select, p {
      padding: 0;
      margin: 0;
      outline: none;
      font-family: Roboto, Arial, sans-serif;
      font-size: 14px;
      color: #666;
      }
      h1 {
      margin: 0;
      font-weight: 400;
      }

      .main-block {
      display: flex;
      justify-content: center;
      align-items: center;
      background: #fff;

      }
      form {
      width: 100%;
      padding: 20px;
      }
      fieldset {
      border: none;
      border-top: 1px solid #8ebf42;
      }
      .account-details, .personal-details {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
      }
      .account-details >div, .personal-details >div >div {
      display: flex;
      align-items: center;
      margin-bottom: 10px;
      }
      .account-details >div, .personal-details >div, input, label {
      width: 100%;
      }
      label {
      padding: 0 5px;
      text-align: right;
      vertical-align: middle;
      }
      input {
      padding: 5px;
      vertical-align: middle;
      }
      .checkbox {
      margin-bottom: 10px;
      }

      .checkbox input, .children input {
      width: auto;
      margin: -2px 10px 0 0;
      }
      .checkbox a {
      color: #8ebf42;
      }
      .checkbox a:hover {
      color: #82b534;
      }
      button {
      width: 100%;
      padding: 10px 0;
      margin: 10px auto;
      border-radius: 5px;
      border: none;
      background: #8ebf42;
      font-size: 14px;
      font-weight: 600;
      color: #fff;
      }
      button:hover {
      background: #82b534;
      }
      @media (min-width: 568px) {
      .account-details >div, .personal-details >div {
      width: 50%;
      }
      label {
      width: 40%;
      }
      input {
      width: 60%;
      }
      }
</style>

</head>
<body>
    <p style="color:red">{{ ErrorMessage }} </p>
    <div class="main-block">
    <form action="{% url 'student:save' %}" method="post">
        <h1>Enter your details</h1>
        {%  csrf_token %}

        <fieldset>

          <div  class="account-details">
            <div><label>Name</label><input type="text" name="name" value="{{ name }}"  ></div>
            <div><label>Roll Number</label><input  name="roll" value="{{ roll }}"></div>
            <div><label>Department</label><input type="text" name="department" value="{{ dept }}"></div>
            <div><label>Hostel</label><input  name="hostel" value="{{ hostel }}"></div>
          </div>
        </fieldset>



        <button type="submit">Submit</button>
    </form>
    </div>
</body>
</html>

Problem1/infoManage/student/templates/student/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit</title>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <style>
      html, body {
      min-height: 100%;
      }
      body, div, form, input, select, p {
      padding: 0;
      margin: 0;
      outline: none;
      font-family: Roboto, Arial, sans-serif;
      font-size: 14px;
      color: #666;
      }
      h1 {
      margin: 0;
      font-weight: 400;
      }

      .main-block {
      display: flex;
      justify-content: center;
      align-items: center;
      background: #fff;

      }
      form {
      width: 100%;
      padding: 20px;
      }
      fieldset {
      border: none;
      border-top: 1px solid #8ebf42;
      }
      .account-details, .personal-details {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
      }
      .account-details >div, .personal-details >div >div {
      display: flex;
      align-items: center;
      margin-bottom: 10px;
      }
      .account-details >div, .personal-details >div, input, label {
      width: 100%;
      }
      label {
      padding: 0 5px;
      text-align: right;
      vertical-align: middle;
      }
      input {
      padding: 5px;
      vertical-align: middle;
      }
      .checkbox {
      margin-bottom: 10px;
      }

      .checkbox input, .children input {
      width: auto;
      margin: -2px 10px 0 0;
      }
      .checkbox a {
      color: #8ebf42;
      }
      .checkbox a:hover {
      color: #82b534;
      }
      button {
      width: 100%;
      padding: 10px 0;
      margin: 10px auto;
      border-radius: 5px;
      border: none;
      background: #8ebf42;
      font-size: 14px;
      font-weight: 600;
      color: #fff;
      }
      button:hover {
      background: #82b534;
      }
      @media (min-width: 568px) {
      .account-details >div, .personal-details >div {
      width: 50%;
      }
      label {
      width: 40%;
      }
      input {
      width: 60%;
      }
      }
</style>

</head>
<body>
    <p style="color:red">{{ ErrorMessage }} </p>
<p style="font-size: 20px; text-align: center; margin-top: 1em; color: black;"> Roll Number : {{ roll }} </p>
<div class="main-block"></div>
    <form action="{% url 'student:editdata' roll %}" method="post">
       <h1>Enter your details</h1>
        {%  csrf_token %}

        <fieldset>

          <div  class="account-details">
            <div><label>Name</label><input type="text" name="name" value="{{ name }}"  ></div>
           {# <div><label>Roll Number</label><input  name="roll" value="{{ roll }}"></div> #}
            <div><label>Department</label><input type="text" name="department" value="{{ department }}"></div>
            <div><label>Hostel</label><input  name="hostel" value="{{ hostel }}"></div>
          </div>
        </fieldset>



        <button type="submit">Submit</button>
    </form>
    </div>
</body>
</html>

Problem1/infoManage/student/templates/student/index.html
<!DOCTYPE html>
<html>

<head>
    <title>Student Data</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <style>
        .button {
  background-color: #4CAF50; /* Green */
  border: none;
  color: white;
  padding: 16px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  transition-duration: 0.4s;
  cursor: pointer;

}
.button2 {
  background-color: white;
  color: black;
  border: 2px solid #008CBA;
}

.button2:hover {
  background-color: #008CBA;
  color: white;
}

table, th, td {
  border: 1px solid black;
  text-align: center;
}


table {
  width: 100%;
  text-align: center;
}
.btn {
  background-color: black;
  border: none;
  color: white;
  padding: 12px 16px;
  font-size: 16px;
  cursor: pointer;
}

/* Darker background on mouse-over */
.btn:hover {
  background-color: grey;
}
    </style>
</head>
<body>
    <div >
        <a style="text-decoration: none" href="{% url 'student:add' %}"><button  class="button button2 " >ADD STUDENT</button></a>
</div>



    <table class="table table-hover">
      <tr class="f">
        <th>Name</th>
        <th>Roll Number</th>
        <th>Department</th>
        <th>Hostel</th>
      </tr>
      {% for entry in studentList %}
      {% if studentList %}

      <tr>
        <td>{{ entry.name }}</td>
        <td>{{ entry.roll }}</td>
        <td>{{entry.department}}</td>
        <td>{{entry.hostel}}</td>
        <td><a href="{% url 'student:delete' entry.roll %}"><button class="btn"><i style="color: white" class="fa fa-trash"></i> </button></a> <a href="{% url 'student:edit' entry.roll %}"><button class="btn" > <i style="color: white" class="far fa-edit" style="font-size:20px"></i></button></a></td>
      </tr>
      {% else %}
<p>No data available</p>

     {% endif %}
     {% endfor %}
    </table>
      </div>
</body>
</html>